
name: cu_demo_publish

on: [push]

jobs:
  publish-computer-use-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the computer-use Docker image
      run: |
        docker build . --tag ghcr.io/ferreat/anthropic-computer-use-demo:latest
        docker run ghcr.io/ferreat/anthropic-computer-use-demo:latest
        docker push ghcr.io/ferreat/anthropic-computer-use-demo:latest
