name: cu_demo_publish

on: [push]

jobs:
  publish-computer-use-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: |
        echo $CR_PAT | docker login ghcr.io -u ferreat --password-stdin
        
      env:
        CR_PAT: ${{ secrets.CR_PAT }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/ferreat/anthropic-computer-use:latest
        docker run ghcr.io/ferreat/anthropic-computer-use:latest
        docker push ghcr.io/ferreat/anthropic-computer-use:latest
